### PR TITLE
Fix duplicate calls of mainStorage.lock() in LockManager for version 1.*

### LINKED ISSUE #164: Trying to acquire a shared dataset lock may cause OverlappingFileLockException
The `class LockManager` manages locks that can be acquired on datasets. It features shared and exclusive locks. Multiple shared locks may be held on a dataset at the same time by different threads.

If a lock is requested, the `lock()` method is called on the `mainStorage` plugin. A typical implementation of that plugin call would try to acquire a file system lock (e.g. do something like calling `java.nio.channels.FileChannel.tryLock​(long position, long size, boolean shared)`), which essentially allows to extend the locking mechanism to external processes.

Now, there is a fundamental design flaw in the `LockManager` implementation: `mainStorage.lock()` is called for each individual lock request. E.g. it is called multiple times for the same dataset, if multiple shared locks are requested. With an implementation of the call in the plugin as sketched above, this will lead to attempting multiple overlapping file system locks, which will cause a `OverlappingFileLockException` to be thrown. As a result, the corresponding thread dies. If this thread is the FSM, the execution of deferred operations stops.

A correct implementation would call `mainStorage.lock()` only once, for the first lock request, keep the returned `AutoCloseable` and close it when the lock count drops to zero.

### PR DESCRIPTION
**Pull request by RKrahl**
- store the storage lock in class LockEntry rather than in class SingleLock,
- as a consequence: obtain only one storage lock when mutliple shared locks are requested on the same dataset,
- release the storage lock when the lock count drops to zero, e.g. when the last lock on the dataset is closed.

This fixes #164 for `ids.server` version 1.*.

### CODE REVIEW

**Comment by RKrahl** [comment]
Note: the CI build and test pipeline fails. But that looks like the  [icat-ansible](https://github.com/icatproject-contrib/icat-ansible) ceased to support the old Java version used to build v1.*. The test succeed when I run them locally.

File: src/main/java/org/icatproject/ids/LockManager.java [hunk 1]
```diff
@@ -134,22 +134,21 @@ public Lock lock(DsInfo ds, LockType type) throws AlreadyLockedException, IOExce
 		synchronized (lockMap) {
 			LockEntry le = lockMap.get(id);
 			if (le == null) {
-				le = new LockEntry(id, type);
+				AutoCloseable storageLock;
+				try {
+					storageLock = mainStorage.lock(ds, type == LockType.SHARED);
+				} catch (AlreadyLockedException | IOException e) {
+					throw e;
```
Comment (GonozalIX) [inline src/main/java/org/icatproject/ids/LockManager.java:141]: The caught exception is immediatelly rethrown here.
Same behaviour as no `try-catch` block.
Add some more logic to the `catch` block (e.g. a logging) or remove the try catch…

File: src/main/java/org/icatproject/ids/LockManager.java [hunk 2]
```diff
@@ -55,6 +57,13 @@ void dec() {
 			count -= 1;
 			if (count == 0) {
 				lockMap.remove(id);
+				if (storageLock != null) {
```
Comment (GonozalIX) [inline src/main/java/org/icatproject/ids/LockManager.java:60]: Why do we need to check `storageLock` to be `null` here?
Should this ever happen? 
If the lock fails an exception is thrown otherwise storageLock is a non-null value?

Comment (RKrahl) [reply src/main/java/org/icatproject/ids/LockManager.java:60]: Yes, this can happen. In fact, it will most of the time. If the storage plugin chooses not to implement file system locking at all, it may use a dummy implementation for `mainStorage.lock()` that simply always returns `null`. This is even the [default](https://github.com/icatproject/ids.plugin/blob/4b94d1076d40fd38a638d8b1f237083aeaa68429/src/main/java/org/icatproject/ids/plugin/AbstractMainStorage.java#L87) in class `AbstractMainStorage`.

Comment (GonozalIX) [reply src/main/java/org/icatproject/ids/LockManager.java:60]: Thanks a lot.

File: src/main/java/org/icatproject/ids/LockManager.java (hunk 1 above)
Comment (RKrahl) [reply src/main/java/org/icatproject/ids/LockManager.java:141]: Indeed, you're right. This code fragment has been moved from [here](https://github.com/icatproject/ids.server/blob/703be1dcf635e43789971eb235b93ecab79143e6/src/main/java/org/icatproject/ids/LockManager.java#L151), where there was a `le.dec();` inbetween, which is not needed in the new version, because the `le` has not been incremented here in the first place.

Still hesitating to remove that though, because it documents in the code that raising `AlreadyLockedException` may also happen in the storage plugin.

Comment (GonozalIX) [reply src/main/java/org/icatproject/ids/LockManager.java:141]: I agree, workaround could be just to add a `logger.debug` information what happened here (or actually failed).

Comment (RKrahl) [reply src/main/java/org/icatproject/ids/LockManager.java]: Ok, I finally opted for the easy solution to simply drop that uneeded try statement. In the end, it's kind of obvious that requesting a lock may fail because the resource is already locked, otherwise you wouldn't need to request the lock in the first place.

**Review by GonozalIX — APPROVED** [review]
